### ISSUE TITLE
Fallo gastos pestaña bank

### ISSUE THREAD

**Issue by javibj** [soker90/betcon#22]
Windows - En la pestaña Bank, al añadir algún ingreso a cualquier casa de apuestas, la app se queda colgada. Una vez cerrada y vuelta a abrir al seleccionar la pestaña Bank, se cuelga la app.

**Comment by soker90** [comment]
No he podido reproducir ese fallo, sube aquí si puedes la base de datos. ¿Que versión de Betcon es?

**Comment by javibj** [comment]
La última para Windows. Te adjunto la base de datos.
[betcon.zip](https://github.com/soker90/betcon/files/1227891/betcon.zip)

**Comment by soker90** [comment]
Listo! Encontré el fallo, parece que Windows maneja las fechas de otra forma, ya está arreglado en la versión en desarrollo para la siguiente versión estará solucionado.

**Comment by soker90** [comment]
Solucionado en la 1.4.3
