### ISSUE TITLE
Crash al editar conjunta de tipsters

### ISSUE THREAD

**Issue by Zegeri** [soker90/betcon#50]
Pasos para reproducir:
* Ir a Tipsters > Historial de pagos > Nueva conjunta
* Pulsar el botón "<", cuya función es eliminar el tipster seleccionado de la conjunta. En este caso, como es una nueva conjunta, no hay tipster para eliminar.

Resultado esperado:
Nada.

Resultado obtenido:
Crash, con el siguiente mensaje en la terminal:
```
Traceback (most recent call last):
  File "/usr/share/betcon/src/new_conjunta.py", line 108, in delete
    self.selected.remove(idTipster)
ValueError: list.remove(x): x not in list
/usr/bin/betcon: línea 2:  3515 Abortado
(`core' generado) python3 "/usr/share/betcon/src/Betcon" "$@"
```

**Comment by soker90** [comment]
Gracias por tu reporte, lo compruebo y lo corrijo para la siguiente versión. 

Si puedes añade la versión de betcon y el sistema operativo cuando hagas un reporte para poder replicar el fallo con mayor facilidad.

**Comment by Zegeri** [comment]
Estoy usando betcon compilado desde código fuente con HEAD en 3e087ae8a2179dc9 (último commit a día de hoy).
Sistema operativo: Manjaro Linux

**Comment by soker90** [comment]
Perfecto entonces. Por si te interesa, mantengo el paquete de betcon en los repos de AUR, siempre lo actualizo al lanzar cada nueva versión estable.
